<?php

namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-09-11 at 11:31:54.
 */
class FormTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Form
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Form();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'Test', 'disabled' => true))->render() [==] '<button disabled type="button" name="test_id" id="test_id">Test</button>'.
     *
     * @covers Kotchasan\Form::button
     */
    public function testButton()
    {

        $this->assertEquals(
            '<button disabled type="button" name="test_id" id="test_id">Test</button>',
            \Kotchasan\Form::button(array('id' => 'test_id', 'value' => 'Test', 'disabled' => true))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'Test', 'disabled' => true, 'tag' => 'input'))->render() [==] '<input disabled type="button" name="test_id" id="test_id" value="Test">'.
     *
     * @covers Kotchasan\Form::button
     */
    public function testButton2()
    {

        $this->assertEquals(
            '<input disabled type="button" name="test_id" id="test_id" value="Test">',
            \Kotchasan\Form::button(array('id' => 'test_id', 'value' => 'Test', 'disabled' => true, 'tag' => 'input'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1))->render() [==] '<input type="checkbox" name="test_id" id="test_id" value=1>'.
     *
     * @covers Kotchasan\Form::checkbox
     */
    public function testCheckbox()
    {

        $this->assertEquals(
            '<input type="checkbox" name="test_id" id="test_id" value=1>',
            \Kotchasan\Form::checkbox(array('id' => 'test_id', 'value' => 1))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label><input type="checkbox" name="test_id" id="test_id" value=1 title="Test">Test</label>'.
     *
     * @covers Kotchasan\Form::checkbox
     */
    public function testCheckbox2()
    {

        $this->assertEquals(
            '<label><input type="checkbox" name="test_id" id="test_id" value=1 title="Test">Test</label>',
            \Kotchasan\Form::checkbox(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item'))->render() [==] '<div class="item"><label><input type="checkbox" name="test_id" id="test_id" value=1 title="Test">&nbsp;Test</label></div>'.
     *
     * @covers Kotchasan\Form::checkbox
     */
    public function testCheckbox3()
    {

        $this->assertEquals(
            '<div class="item"><label><input type="checkbox" name="test_id" id="test_id" value=1 title="Test">&nbsp;Test</label></div>',
            \Kotchasan\Form::checkbox(array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-valid'))->render() [==] '<div class="item"><label class="icon-valid"><input type="checkbox" name="test_id" id="test_id" value=1 title="Test">&nbsp;Test</label></div>'.
     *
     * @covers Kotchasan\Form::checkbox
     */
    public function testCheckbox4()
    {

        $this->assertEquals(
            '<div class="item"><label class="icon-valid"><input type="checkbox" name="test_id" id="test_id" value=1 title="Test">&nbsp;Test</label></div>',
            \Kotchasan\Form::checkbox(array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-valid'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="text" class="color" name="test_id" id="test_id" value="#FFF" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::color
     */
    public function testColor()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="text" class="color" name="test_id" id="test_id" value="#FFF" title="Test"></label>',
            \Kotchasan\Form::color(array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-color'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-color"><input type="text" class="color" name="test_id" id="test_id" value="#FFF" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::color
     */
    public function testColor2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-color"><input type="text" class="color" name="test_id" id="test_id" value="#FFF" title="Test"></span></div>',
            \Kotchasan\Form::color(array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-color'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="text" class="currency" name="test_id" id="test_id" value=1 title="Test"></label>'.
     *
     * @covers Kotchasan\Form::currency
     */
    public function testCurrency()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="text" class="currency" name="test_id" id="test_id" value=1 title="Test"></label>',
            \Kotchasan\Form::currency(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 100, 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-money'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-money"><input type="text" class="currency" name="test_id" id="test_id" value=100 title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::currency
     */
    public function testCurrency2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-money"><input type="text" class="currency" name="test_id" id="test_id" value=100 title="Test"></span></div>',
            \Kotchasan\Form::currency(array('id' => 'test_id', 'value' => 100, 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-money'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="date" name="test_id" id="test_id" value=1 title="Test"></label>'.
     *
     * @covers Kotchasan\Form::date
     */
    public function testDate()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="date" name="test_id" id="test_id" value=1 title="Test"></label>',
            \Kotchasan\Form::date(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-calendar'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-calendar"><input type="date" name="test_id" id="test_id" value="#FFF" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::date
     */
    public function testDate2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-calendar"><input type="date" name="test_id" id="test_id" value="#FFF" title="Test"></span></div>',
            \Kotchasan\Form::date(array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-calendar'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '2021-01-01 12:00', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="datetime" name="test_id" id="test_id" value="2021-01-01 12:00" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::datetime
     */
    public function testDatetime()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="datetime" name="test_id" id="test_id" value="2021-01-01 12:00" title="Test"></label>',
            \Kotchasan\Form::datetime(array('id' => 'test_id', 'value' => '2021-01-01 12:00', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '2021-01-01 12:00', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-calendar'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-calendar"><input type="datetime" name="test_id" id="test_id" value="2021-01-01 12:00" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::datetime
     */
    public function testDatetime2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-calendar"><input type="datetime" name="test_id" id="test_id" value="2021-01-01 12:00" title="Test"></span></div>',
            \Kotchasan\Form::datetime(array('id' => 'test_id', 'value' => '2021-01-01 12:00', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-calendar'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="email" name="test_id" id="test_id" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::email
     */
    public function testEmail()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="email" name="test_id" id="test_id" title="Test"></label>',
            \Kotchasan\Form::email(array('id' => 'test_id', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-email'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-email"><input type="email" name="test_id" id="test_id" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::email
     */
    public function testEmail2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-email"><input type="email" name="test_id" id="test_id" title="Test"></span></div>',
            \Kotchasan\Form::email(array('id' => 'test_id', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-email'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="file" class="g-file" name="test_id" id="test_id" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::file
     */
    public function testFile()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="file" class="g-file" name="test_id" id="test_id" title="Test"></label>',
            \Kotchasan\Form::file(array('id' => 'test_id', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-file'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-file"><input type="file" class="g-file" name="test_id" id="test_id" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::file
     */
    public function testFile2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-file"><input type="file" class="g-file" name="test_id" id="test_id" title="Test"></span></div>',
            \Kotchasan\Form::file(array('id' => 'test_id', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-file'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1))->render() [==] '<input type="hidden" name="test_id" id="test_id" value=1>'.
     *
     * @covers Kotchasan\Form::hidden
     */
    public function testHidden()
    {

        $this->assertEquals(
            '<input type="hidden" name="test_id" id="test_id" value=1>',
            \Kotchasan\Form::hidden(array('id' => 'test_id', 'value' => 1))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="number" name="test_id" id="test_id" value=1 title="Test"></label>'.
     *
     * @covers Kotchasan\Form::number
     */
    public function testNumber()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="number" name="test_id" id="test_id" value=1 title="Test"></label>',
            \Kotchasan\Form::number(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1234, 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-number'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-number"><input type="number" name="test_id" id="test_id" value=1234 title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::number
     */
    public function testNumber2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-number"><input type="number" name="test_id" id="test_id" value=1234 title="Test"></span></div>',
            \Kotchasan\Form::number(array('id' => 'test_id', 'value' => 1234, 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-number'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="integer" name="test_id" id="test_id" value=1 title="Test"></label>'.
     *
     * @covers Kotchasan\Form::integer
     */
    public function testInteger()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="integer" name="test_id" id="test_id" value=1 title="Test"></label>',
            \Kotchasan\Form::integer(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => -100, 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-number'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-number"><input type="integer" name="test_id" id="test_id" value=-100 title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::integer
     */
    public function testInteger2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-number"><input type="integer" name="test_id" id="test_id" value=-100 title="Test"></span></div>',
            \Kotchasan\Form::integer(array('id' => 'test_id', 'value' => -100, 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-number'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '1234', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="password" name="test_id" id="test_id" value="1234" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::password
     */
    public function testPassword()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="password" name="test_id" id="test_id" value="1234" title="Test"></label>',
            \Kotchasan\Form::password(array('id' => 'test_id', 'value' => '1234', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '1234', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-color'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-color"><input type="password" name="test_id" id="test_id" value="1234" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::password
     */
    public function testPassword2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-color"><input type="password" name="test_id" id="test_id" value="1234" title="Test"></span></div>',
            \Kotchasan\Form::password(array('id' => 'test_id', 'value' => '1234', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-color'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1))->render() [==] '<input type="radio" name="test_id" id="test_id" value=1>'.
     *
     * @covers Kotchasan\Form::radio
     */
    public function testRadio()
    {

        $this->assertEquals(
            '<input type="radio" name="test_id" id="test_id" value=1>',
            \Kotchasan\Form::radio(array('id' => 'test_id', 'value' => 1))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label><input type="radio" name="test_id" id="test_id" value=1 title="Test">Test</label>'.
     *
     * @covers Kotchasan\Form::radio
     */
    public function testRadio2()
    {

        $this->assertEquals(
            '<label><input type="radio" name="test_id" id="test_id" value=1 title="Test">Test</label>',
            \Kotchasan\Form::radio(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item'))->render() [==] '<div class="item"><label for="test_id">Test</label><span><input type="radio" name="test_id" id="test_id" value=1 title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::radio
     */
    public function testRadio3()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span><input type="radio" name="test_id" id="test_id" value=1 title="Test"></span></div>',
            \Kotchasan\Form::radio(array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-valid'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-valid"><input type="radio" name="test_id" id="test_id" value=1 title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::radio
     */
    public function testRadio4()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-valid"><input type="radio" name="test_id" id="test_id" value=1 title="Test"></span></div>',
            \Kotchasan\Form::radio(array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-valid'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="range" name="test_id" id="test_id" value=1 title="Test"></label>'.
     *
     * @covers Kotchasan\Form::range
     */
    public function testRange()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="range" name="test_id" id="test_id" value=1 title="Test"></label>',
            \Kotchasan\Form::range(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item'))->render() [==] '<div class="item"><label for="test_id">Test</label><div><input type="range" name="test_id" id="test_id" value=1 title="Test"></div></div>'.
     *
     * @covers Kotchasan\Form::range
     */
    public function testRange2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><div><input type="range" name="test_id" id="test_id" value=1 title="Test"></div></div>',
            \Kotchasan\Form::range(array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'itemClass' => 'item'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'Test', 'disabled' => true))->render() [==] '<button disabled type="reset" name="test_id" id="test_id">Test</button>'.
     *
     * @covers Kotchasan\Form::reset
     */
    public function testReset()
    {

        $this->assertEquals(
            '<button disabled type="reset" name="test_id" id="test_id">Test</button>',
            \Kotchasan\Form::reset(array('id' => 'test_id', 'value' => 'Test', 'disabled' => true))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'Test', 'disabled' => true, 'tag' => 'input'))->render() [==] '<input disabled type="reset" name="test_id" id="test_id" value="Test">'.
     *
     * @covers Kotchasan\Form::reset
     */
    public function testReset2()
    {

        $this->assertEquals(
            '<input disabled type="reset" name="test_id" id="test_id" value="Test">',
            \Kotchasan\Form::reset(array('id' => 'test_id', 'value' => 'Test', 'disabled' => true, 'tag' => 'input'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'options' => [0 => 0, 1 => 1]))->render() [==] '<label>Test&nbsp;<select name="test_id" id="test_id" title="Test"><option value=0>0</option><option value=1 selected>1</option></select></label>'.
     *
     * @covers Kotchasan\Form::select
     */
    public function testSelect()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<select name="test_id" id="test_id" title="Test"><option value=0>0</option><option value=1 selected>1</option></select></label>',
            \Kotchasan\Form::select(array('id' => 'test_id', 'value' => 1, 'label' => 'Test', 'options' => [0 => 0, 1 => 1]))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-color', 'options' => [0 => 0, 1 => 1]))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-color"><select name="test_id" id="test_id" title="Test"><option value=0 selected>0</option><option value=1>1</option></select></span></div>'.
     *
     * @covers Kotchasan\Form::select
     */
    public function testSelect2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-color"><select name="test_id" id="test_id" title="Test"><option value=0 selected>0</option><option value=1>1</option></select></span></div>',
            \Kotchasan\Form::select(array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-color', 'options' => [0 => 0, 1 => 1]))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'Test', 'disabled' => true))->render() [==] '<button disabled type="submit" name="test_id" id="test_id">Test</button>'.
     *
     * @covers Kotchasan\Form::submit
     */
    public function testSubmit()
    {

        $this->assertEquals(
            '<button disabled type="submit" name="test_id" id="test_id">Test</button>',
            \Kotchasan\Form::submit(array('id' => 'test_id', 'value' => 'Test', 'disabled' => true))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'Test', 'disabled' => true, 'tag' => 'input'))->render() [==] '<input disabled type="submit" name="test_id" id="test_id" value="Test">'.
     *
     * @covers Kotchasan\Form::submit
     */
    public function testSubmit2()
    {

        $this->assertEquals(
            '<input disabled type="submit" name="test_id" id="test_id" value="Test">',
            \Kotchasan\Form::submit(array('id' => 'test_id', 'value' => 'Test', 'disabled' => true, 'tag' => 'input'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '0123456789', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="tel" name="test_id" id="test_id" value="0123456789" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::tel
     */
    public function testTel()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="tel" name="test_id" id="test_id" value="0123456789" title="Test"></label>',
            \Kotchasan\Form::tel(array('id' => 'test_id', 'value' => '0123456789', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '0123456789', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-phone'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-phone"><input type="tel" name="test_id" id="test_id" value="0123456789" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::tel
     */
    public function testTel2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-phone"><input type="tel" name="test_id" id="test_id" value="0123456789" title="Test"></span></div>',
            \Kotchasan\Form::tel(array('id' => 'test_id', 'value' => '0123456789', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-phone'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="text" name="test_id" id="test_id" value=1 title="Test"></label>'.
     *
     * @covers Kotchasan\Form::text
     */
    public function testText()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="text" name="test_id" id="test_id" value=1 title="Test"></label>',
            \Kotchasan\Form::text(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-color'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-color"><input type="text" name="test_id" id="test_id" value="#FFF" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::text
     */
    public function testText2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-color"><input type="text" name="test_id" id="test_id" value="#FFF" title="Test"></span></div>',
            \Kotchasan\Form::text(array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-color'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<textarea name="test_id" id="test_id" title="Test">1</textarea></label>'.
     *
     * @covers Kotchasan\Form::textarea
     */
    public function testTextarea()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<textarea name="test_id" id="test_id" title="Test">1</textarea></label>',
            \Kotchasan\Form::textarea(array('id' => 'test_id', 'value' => 1, 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-file'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-file"><textarea name="test_id" id="test_id" title="Test">#FFF</textarea></span></div>'.
     *
     * @covers Kotchasan\Form::textarea
     */
    public function testTextarea2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-file"><textarea name="test_id" id="test_id" title="Test">#FFF</textarea></span></div>',
            \Kotchasan\Form::textarea(array('id' => 'test_id', 'value' => '#FFF', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-file'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '00:00', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="time" name="test_id" id="test_id" value="00:00" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::time
     */
    public function testTime()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="time" name="test_id" id="test_id" value="00:00" title="Test"></label>',
            \Kotchasan\Form::time(array('id' => 'test_id', 'value' => '00:00', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => '00:00', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-clock'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-clock"><input type="time" name="test_id" id="test_id" value="00:00" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::time
     */
    public function testTime2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-clock"><input type="time" name="test_id" id="test_id" value="00:00" title="Test"></span></div>',
            \Kotchasan\Form::time(array('id' => 'test_id', 'value' => '00:00', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-clock'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'kotchasan.com', 'label' => 'Test'))->render() [==] '<label>Test&nbsp;<input type="url" name="test_id" id="test_id" value="kotchasan.com" title="Test"></label>'.
     *
     * @covers Kotchasan\Form::url
     */
    public function testUrl()
    {

        $this->assertEquals(
            '<label>Test&nbsp;<input type="url" name="test_id" id="test_id" value="kotchasan.com" title="Test"></label>',
            \Kotchasan\Form::url(array('id' => 'test_id', 'value' => 'kotchasan.com', 'label' => 'Test'))->render()
        );
    }

    /**
     * Generated from @assert (array('id' => 'test_id', 'value' => 'kotchasan.com', 'label' => 'Test', 'itemClass' => 'item' , 'labelClass' => 'icon-world'))->render() [==] '<div class="item"><label for="test_id">Test</label><span class="icon-world"><input type="url" name="test_id" id="test_id" value="kotchasan.com" title="Test"></span></div>'.
     *
     * @covers Kotchasan\Form::url
     */
    public function testUrl2()
    {

        $this->assertEquals(
            '<div class="item"><label for="test_id">Test</label><span class="icon-world"><input type="url" name="test_id" id="test_id" value="kotchasan.com" title="Test"></span></div>',
            \Kotchasan\Form::url(array('id' => 'test_id', 'value' => 'kotchasan.com', 'label' => 'Test', 'itemClass' => 'item', 'labelClass' => 'icon-world'))->render()
        );
    }
}