<?php

namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-12-18 at 08:55:29.
 */
class PasswordTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Password
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Password();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert (Password::encode("ทดสอบภาษาไทย", 12345678), 12345678) [==] "ทดสอบภาษาไทย".
     *
     * @covers Kotchasan\Password::decode
     */
    public function testDecode()
    {

        $this->assertEquals(
          "ทดสอบภาษาไทย",
          \Kotchasan\Password::decode(Password::encode("ทดสอบภาษาไทย", 12345678), 12345678)
        );
    }

    /**
     * Generated from @assert (Password::encode(1234, 12345678), 12345678) [==] 1234.
     *
     * @covers Kotchasan\Password::decode
     */
    public function testDecode2()
    {

        $this->assertEquals(
          1234,
          \Kotchasan\Password::decode(Password::encode(1234, 12345678), 12345678)
        );
    }
}