<?php

namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-03-13 at 22:52:14.
 */
class PromptpayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Promptpay
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert ('0123456789')->payload() [==] '00020101021129370016A000000677010111011300661234567895802TH530376463047CC1'.
     *
     * @covers Kotchasan\Promptpay::create
     */
    public function testCreate()
    {

        $this->assertEquals(
            '00020101021129370016A000000677010111011300661234567895802TH530376463047CC1',
            \Kotchasan\Promptpay::create('0123456789')->payload()
        );
    }

    /**
     * Generated from @assert ('660123456789')->payload() [==] '00020101021129370016A000000677010111011300661234567895802TH530376463047CC1'.
     *
     * @covers Kotchasan\Promptpay::create
     */
    public function testCreate2()
    {

        $this->assertEquals(
            '00020101021129370016A000000677010111011300661234567895802TH530376463047CC1',
            \Kotchasan\Promptpay::create('660123456789')->payload()
        );
    }

    /**
     * Generated from @assert ('660123456789', 99)->payload() [==] '00020101021229370016A000000677010111011300661234567895802TH5303764540599.00630472B'.
     *
     * @covers Kotchasan\Promptpay::create
     */
    public function testCreate3()
    {

        $this->assertEquals(
            '00020101021229370016A000000677010111011300661234567895802TH5303764540599.00630472B',
            \Kotchasan\Promptpay::create('660123456789', 99)->payload()
        );
    }

    /**
     * Generated from @assert ('66123456789')->payload() [==] '00020101021129370016A000000677010111011300661234567895802TH530376463047CC1'.
     *
     * @covers Kotchasan\Promptpay::create
     */
    public function testCreate4()
    {

        $this->assertEquals(
            '00020101021129370016A000000677010111011300661234567895802TH530376463047CC1',
            \Kotchasan\Promptpay::create('66123456789')->payload()
        );
    }

    /**
     * Generated from @assert ('123456789012')->payload() [==] '00020101021129370016A000000677010111011301234567890125802TH530376463048AF8'.
     *
     * @covers Kotchasan\Promptpay::create
     */
    public function testCreate5()
    {

        $this->assertEquals(
            '00020101021129370016A000000677010111011301234567890125802TH530376463048AF8',
            \Kotchasan\Promptpay::create('123456789012')->payload()
        );
    }
}