<?php

namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-03-06 at 13:33:32.
 */
class ProvinceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Province
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Province();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert (10) [==] 'กรุงเทพมหานคร'.
     *
     * @covers Kotchasan\Province::get
     */
    public function testGet()
    {

        $this->assertEquals(
          'กรุงเทพมหานคร',
          \Kotchasan\Province::get(10)
        );
    }
}