<?php
namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-24 at 13:52:31.
 */
class ValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Validator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Validator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert ('admin@localhost.com') [==] true.
     *
     * @covers Kotchasan\Validator::email
     */
    public function testEmail()
    {

        $this->assertTrue(
            \Kotchasan\Validator::email('admin@localhost.com')
        );
    }

    /**
     * Generated from @assert ('admin@localhost') [==] true.
     *
     * @covers Kotchasan\Validator::email
     */
    public function testEmail2()
    {

        $this->assertTrue(
            \Kotchasan\Validator::email('admin@localhost')
        );
    }

    /**
     * Generated from @assert ('ทดสอบ@localhost') [==] false.
     *
     * @covers Kotchasan\Validator::email
     */
    public function testEmail3()
    {

        $this->assertFalse(
            \Kotchasan\Validator::email('ทดสอบ@localhost')
        );
    }
}
